import styles from './page.module.css'
import Image from 'next/image'
import Footer from '@/app/components/footer'
import { Reference, Footnote } from '@/app/components/buttons';


export default async function Article() {
    const author = 'Olivia Hu';
    const credit = 'Photo by Matthew Lai';
    const title = 'His story & mine';
    const date = 'April 23, 2025'

    return (
        <div>
            <div className={styles.main}>
                <div className={styles.container}>
                    <Image 
                        className={styles.image}
                        src='/issues/25s/his-story-and-mine.webp'
                        width={600}
                        height={600}
                        alt='article image'/>
                    <p className = {styles.credit}>{credit}</p>
                    <h1 className={styles.title}>{title}</h1>
                    <h2 className={styles.author}>BY {author.toUpperCase()}</h2>
                    <h3 className={styles.date}>{date}</h3>
                    <div className={styles.text}>
                        A man, a woman, and a garden. <br/><br/>
                        For most of us, these symbols instinctively recall Adam, Eve, and the Garden of Eden. And that&apos;s to be expected: the story is a Sunday school classic, and it&apos;s had an undeniable influence on culture and art for millennia. It&apos;s a story told so commonly it&apos;s become commonplace; as in, the intrigue and awe of <i>what actually happened</i> is lost on the general viewer given our familiarity of its symbols. I personally thought I knew the story well, like the back of my hand, but maybe I knew it more like the actual back of my hand &mdash; as a shadow or afterimage just outside my conscious memory.  <br/><br/>
                        It was more recently, upon returning to the text, that I gained a clearer picture of the story of the Fall. I began noticing how the text unveiled facets of God&apos;s character &mdash; His authority, His righteousness, and most strikingly, His gentle kindness. What appears to be a tragedy is really the start of the great biblical story &mdash; God&apos;s love letter to us. As I&apos;ve grown deeper in faith, God has used this familiar, well-worn story to write into the chapters of my life &mdash; I&apos;d like to share a bit of that with you today. <br/><br/>
                        For the second half of last semester, starting in October 2025, I took an extended leave from campus and returned home due to medical complications. In moving back, I felt abruptly removed from my church community on campus, which was my spiritual home. The brothers and sisters there encouraged and sharpened me, kept me accountable in faith, allowed me opportunities to serve, and continually inspired me of Christ&apos;s character. While my experience differs greatly, especially in magnitude, from Adam and Eve&apos;s, I could relate to the sense of banishment. The environment shift was destabilizing, especially in sudden separation from the presence of God, which dwelled so tangibly upon my church community. As I wrestled with both my physical health and fears about the future, I felt lost. And I wondered, why had God removed me so forcibly from my home, my source of life? <br/><br/>
                        <br/>
                        <b>I. I don&apos;t know what&apos;s good for me</b><br/>
                        Life was really good on campus. In a way, I&apos;d been building a little Eden of my own: I&apos;d found a church and community I really loved; I was in a happy relationship; I had a car, which granted a sense of unlimited freedom; and my education at Georgia Tech held promising outcomes for my career and future. My life spoke of the wealthy abundance of God&apos;s provision, and I did my best to honor His kindness through service and devotion. Fruitful living and intimacy with God &mdash; yes, my personal Eden. <br/><br/>
                        This period was not unsimilar to King Solomon&apos;s reign, during which he built the Temple in Jerusalem for the Lord (1 Kings 6-8). The temple is understood to represent the garden of Eden, based on symbolic parallels in imagery, ornamentation, and the creation process of both <q>gardens</q> (Joo). King Solomon spent seven years building this temple, pouring in great efforts and wealth for labor costs and precious building materials. However, between the descriptions of the temple&apos;s construction in 1 Kings 6-8, we learn that Solomon was simultaneously building his own palace, to which he devoted double the time (13 years) and many times more wealth and attention. The house he built for himself was, as a result, far larger and more ornate than the house he built for the Lord.  <br/><br/>
                        So I ask: in what areas of my life have I been worshipping myself more than I have been worshipping Him? The answer grew increasingly clear during my period of struggle at home. My church community had become my source of laughter and joy, far more than the word of God (Psalm 1:2); my boyfriend had become my comfort and foundation before prayer and faith; my car had become a space for selfish escape where I should have engaged with my brothers and sisters; and my academics had become my pride and security over my identity in Christ. I gave God whatever was left over, which may have been substantial, but paled in comparison to the devotion I gave myself.  <br/><br/>
                        A state of such self-centeredness is a precarious place to be, and can lead to much worse, as with King Solomon: near the end of his life, Solomon turned to idol worship, building temples to foreign gods to please his foreign wives (1 Kings 11:8-9). This was the wisest man in all of history, the builder of the Lord&apos;s temple, now turned to apostasy. So the Lord stripped the kingdom away from Solomon&apos;s lineage after his death, resulting in Israel&apos;s Split into the northern and southern kingdoms (1 Kings 11:31-33). Solomon, it seemed, had grown too wise in his own eyes, for we know that God <q>will destroy the wisdom of the wise, and the discernment of the discerning [He] will thwart</q> (1 Corinthians 1:19).  <br/><br/>
                        I experienced a similar <q>dethroning</q> during that same period, though again, not to the same degree as Solomon&apos;s. It happened rapidly, within a period of two weeks, with a car accident, a break up, and my leave from campus. When those foundational comforts disappeared, it became clear that the <q>Eden</q> I&apos;d been experiencing was only a facsimile of the real thing. As gratitude and dependence strayed towards idolatry, God graciously took these things away from me, that I might repent and return to the true foundation and treasure &mdash; Him. <br/><br/>
                        I don&apos;t know what&apos;s good for me. But He does. <br/><br/>
                        <br/>
                        <b>II. I&apos;ve fallen and I can&apos;t get up!</b><br/>
                        Let&apos;s return to Adam and Eve and after the Fall. The two were cast out of the garden, cursed to a life of toil, and forever barred from the Tree of Life with no hope of reconciliation.  <br/><br/>
                        Still, to reduce the Fall to a pure tragedy overlooks a few important takeaways: (1) God is just and perfect. When Adam and Eve ate the forbidden fruit and disobeyed God, their sin was incompatible with God&apos;s perfection and it drove a wedge between them. Further intimacy with God was no longer possible, and what is death but separation from Him? So the wage of their sin was death (Romans 6:23), and they were cursed to be apart from Him forever.  <br/><br/>
                        But, (2) their sin did not hinder His love. Despite the sin that separated them, God continued to love Adam and Eve. Yes, God exiled them from the garden of Eden, but He did so <q>lest [Adam] reach out his hand and take also of the tree of life and eat, and live forever</q> (Genesis 3:22). He banished them, so they would not live forever in separation from Him: it was in mercy and in love that God removed Adam and Eve from the garden. And from the moment of separation, He began to work to bring them back.  <br/><br/>
                        These two truths are also written into my own story. Upon leaving campus, I felt I&apos;d fallen: I was physically weakened and humbled, my consistent academic record was marred with Withdrawals, and the relationships and church that bolstered my faith were suddenly swept away far beyond my reach. But I realized I&apos;d grown entitled to undeserved blessings &mdash; <q>what do you have that you did not receive?</q> (1 Cor. 4:7) &mdash; and these gifts were rightly His to take away. In their absence, He revealed where my foundation stood upon His gifts instead of Him alone. I was able to see the trajectory of my sin and its incompatibility with His perfection, and subsequently repent with more clarity. My time at home wasn&apos;t easy; it was a season of physical resilience, spiritual refinement and quiet solitude. But it was also a time to rest and re-center, which brought much reassurance and warmth in my relationship with Him. It wasn&apos;t banishment; rather, it was a testament to His faithful pursuit of my heart and His prudent protection of my faith. So when I look back, all I see is His love and mercy, all to His glory. <br/><br/>
                        We live in a fallen world. The reality Adam and Eve lived in after the Fall was marked by pain, toil, and futility, with a prescribed ending: <q>to dust you shall return</q> (Genesis 3:19). And the cycle of sin and pain has only worsened since then, establishing war, greed, violence, and constant enmity as our new status quo. Suffering, then, is to be expected, as <q>all who desire to live a godly life in Christ Jesus will be persecuted, while evil people and impostors will go on from bad to worse, deceiving and being deceived</q> (2 Timothy 3:12).  <br/><br/>
                        But there is suffering and there is true evil, and I&apos;ve come to learn that suffering is actually good, as Apostle Paul writes, <q>suffering produces endurance, and endurance produces character, and character produces hope</q> (Romans 5:3-5).<Reference number={1} /> In fact, <i>only one bad thing has ever happened, and that is the death of Jesus.</i>  <br/><br/>
                        It&apos;s simple yet subversive. The just punishment for human sin is death, or eternal separation from God. Jesus, who never sinned and hence never left the intimacy of God, not only chose to die, descending into the pits of Hell, but he also chose to shoulder the burdens of the whole world, paying the wage of death once and for all to save us. Jesus&apos; death was <q>bad</q> because it was wholly undeserved and excruciatingly painful, and yet we celebrate Good Friday because of the hope his resurrection offers. He rose and overcame death, and through him alone we can be reconciled with God, our first and most intimate Friend.  <br/><br/>
                        Where the world fell and couldn&apos;t get back up, God had been planning from the beginning to save us.  <br/><br/>
                        <br/>
                        On December 31, I was discharged from treatment, quite a few weeks earlier than my projected recovery date. My early discharge can be attributed in part to my youth and lack of prior medical complications, but the key difference I observed between myself and other patients wasn&apos;t physical &mdash; the difference was hope. Treatment was a mindset battle more than anything else, and a lack of mental fortitude often resulted in a longer recovery time. There were times when recovery seemed impossibly distant; there were times when I felt I&apos;d never be able to get back up.  <br/><br/>
                        But, in His mercy, God planted a hope in me that refused to peter out. I held onto the truth that God had revealed to me: the worst thing has already happened, and in Christ, death is overcome. His power is absolute and Jesus&apos; grace is sufficient for all my weaknesses (2 Corinthians 12:9). Regardless of my physical progress, I knew that all was good, all was well, so long as He was glorified. And He consoled me, shepherded me, and redeemed me, so that miraculously, I was healed in Jesus&apos; name.<sup>2</sup> <br/><br/>
                        The hope that buoyed me at home morphed into an uncontainable joy as I returned to campus. Each day is one lived out in gratitude, because I know whether I&apos;m here on campus or at home or anywhere else, I&apos;m known and established by an unchanging, everlasting God. As descendants of Adam and Eve, we all live in a state of banishment, which is to say that the Tree of Life, the meaning of life, is nowhere to be found on earth, but only in the hope of reconciling with Him. Isn&apos;t that so freeing? Each day is a bookmark in His story and mine, a chance to admire His workmanship and give all the praise and glory to Him.  <br/><br/>
                        To Him: blessing and honor and glory and might, forever and ever (Revelation 5:13). <br/><br/>
                        Amen.
                    </div>
                    <div className="mt-8 leading-6">
                        <p className="mb-3 font-bold">Footnotes</p>
                        <Footnote number={1} text={`There is much more to say about Christian suffering, but I'll avoid derailing us here`}/> <br/>
                        <sup>2</sup> Always happy to share more about my testimony!
                    </div>
                </div>
            </div>
            <div className={styles.footer}>
                <Footer />
            </div>
        </div>
)};
